name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: workly_db  # Usamos workly_db en vez de testdb
          MYSQL_USER: ${{ secrets.DB_USER }}  # Usar un secreto para el usuario
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Usar un secreto para la contraseña
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      # Paso 1: Comprobar el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar JDK 21 (asegúrate de que coincida con tu versión local)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Paso 3: Configurar el caché de Maven (para acelerar las dependencias)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Paso 4: Cambiar al directorio donde está el archivo pom.xml y ejecutar Maven para backend
      - name: Build and test Backend
        run: |
          cd BackEnd/TFG-Workly  # Cambiar al directorio donde está el archivo pom.xml
          mvn clean test -Dspring.profiles.active=github -Dspring.datasource.url=jdbc:mysql://localhost:3306/workly_db -Dspring.datasource.username=${{ secrets.DB_USER }} -Dspring.datasource.password=${{ secrets.DB_PASSWORD }}

      # Paso 5: Configuración para el Frontend (React)
      - name: Set up Node.js and Install dependencies for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Usa la versión de Node.js que necesitas
          
      - name: Install dependencies for Frontend
        run: |
          cd FrontEnd/frontend  # Cambia al directorio donde se encuentra tu frontend
          npm install  # Instala las dependencias de React y Tailwind

      - name: Build Frontend
        run: |
          cd FrontEnd/frontend  # Cambia al directorio donde se encuentra tu frontend
          npm run build  # Genera la versión de producción del frontend

      # Paso 6: Realizar el análisis de SonarQube
      - name: SonarQube Analysis
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-login: ${{ secrets.SONAR_TOKEN }}
